# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
trigger:
- main

pool:
  name: Default

steps:
- task: CmdLine@2
  displayName: 'DOWNLOAD AND INSTALL AQUASEC TRIVY'
  inputs:
    script: |
      sudo apt-get install wget apt-transport-https gnupg lsb-release
      wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
      echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
      sudo apt-get update
      sudo apt-get install trivy
      trivy -v

- task: CmdLine@2
  displayName: 'Run Trivy Scan'
  inputs:
    script: |
      trivy image --format table \
                  --output trivy-image-report.html \
                  hadil0505/haki_app:back_final
      pwd
      ls -al # List files to verify the report is created

- task: CmdLine@2
  displayName: 'Move Trivy Report to the Pipeline Workspace'
  inputs:
    script: |
      mv trivy-image-report.html $(System.DefaultWorkingDirectory)/trivy-image-report.html

- task: PublishPipelineArtifact@1
  displayName: 'Publish Trivy Report'
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/trivy-image-report.html'
    artifactName: 'trivy-reports'
    publishLocation: 'pipeline'

