# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
trigger:
- main

pool:
  name: Default

variables:
  nodeVersion: '14.x'  # Using a modern Node.js version
  backendImageNameTag: 'hakiBackend'
  dockerHubRepository: 'hadil0505/haki_app'
  dockerHubImageName: 'web-framework-backend'

steps:


- task: Docker@2
  displayName: 'Build Backend Docker Image'
  inputs:
    containerRegistry: 'dockerHub_connection'
    repository: '$(dockerHubRepository)'
    Dockerfile: '**/Dockerfile'  # Path to your Dockerfile
    tags: |
      $(backendImageNameTag)
